"""Single complete decoder layer to qualify attention-to-MoE handoff."""
from pathlib import Path
from build_full_layout import build
ROOT=Path(__file__).resolve().parents[1]

def main():
    full=build();s=full.split('  // Original 201088 vocabulary rows')[0]
    s=s.replace('.width=750','.width=27').replace('@set_rectangle(750,1160)','@set_rectangle(27,1160)')
    s=s.replace('for(@range(i16,24))|layer|','for(@range(i16,1))|layer|').replace('const b:i16=46+27*layer','const b:i16=0')
    s=s.replace('"attention_controller_full.csl"','"attention_controller.csl"').replace(',.first_layer=layer==0','')
    s=s.replace('.embedding_return=layer==0 and x==0','.embedding_return=false')
    s=s.replace('    }else if(x==1 and y>=1054', '''    }else if(x==0 and y==1158){
      @set_tile_code(b+x,y,"endpoint.csl",.{.memcpy_params=memcpy.get_params(b+x),.ingress=true,.egress=false});
    }else if(x==1 and y>=1054''')
    s=s.replace('    @set_color_config(b+26,0,@get_color(12),.{.routes=.{.rx=.{RAMP},.tx=.{EAST}}});','')
    attn=(ROOT/'experiments/attention_prefix/layout.csl').read_text()
    routes='  // West original residual'+attn.split('  // West original residual')[1].split('  // Normalized input fans')[0]
    exports='  @export_name("identity"'+full.split('  @export_name("identity"')[1]
    s=s.replace('// Generated by tools/build_full_layout.py. Full original GPT-OSS-20B, 24 layers.','// Generated single original decoder-layer diagnostic; no full-model claim.')
    path=ROOT/'experiments/decoder_layer/layout.csl';path.parent.mkdir(parents=True,exist_ok=True);path.write_text(s+routes+exports)
    (path.parent/'endpoint.csl').write_text((ROOT/'experiments/attention_prefix/endpoint.csl').read_text())
    print(path)

if __name__=='__main__':main()
