"""Assemble proven attention/MoE route blocks with full vocabulary and layer links.

The generated CSL is ordinary source, independently compiler-checked. No host
tensor forwarding is introduced by this layout generator.
"""
import re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def shift_routes(source):
    return re.sub(r'@set_color_config\(([^,]+),',r'@set_color_config(b+(\1),',source)

def build():
    attention=(ROOT/'experiments/attention_prefix/layout.csl').read_text()
    moe=(ROOT/'experiments/moe_layer/layout.csl').read_text()
    prefix_routes=attention.split('  // Normalized input fans')[1].split('  @export_name(')[0]
    moe_routes=moe.split('  // Full router:')[1].split('  @export_name(')[0]
    # The standalone ingress is removed; attention supplies the MoE hidden state.
    prefix_routes='  // Normalized input fans'+prefix_routes
    moe_routes='  // Full router:'+moe_routes
    placements=moe.split('  for(@range(i16,27))|x|{for(@range(i16,1160))|y|{')[1].split('  // West hidden input;')[0]
    placements=placements.rsplit('  }}',1)[0]
    start=placements.index('    if(x==1 and y>=1054')
    placements=placements[:start]+'''    if((x==0 and y<1140) or (x==1 and y<60)){
      @set_tile_code(x,y,"projection_full.csl",.{.memcpy_params=memcpy.get_params(x),.kind=@as(u16,x),
        .first=y%30==0,.last=y%30==29,.parity=@as(u16,(y%30)%2),.embedding_return=layer==0 and x==0,.return_root=y==0});
    }else if(x==1 and y>=64 and y<1053){
      @set_tile_code(x,y,"projection_full.csl",.{.memcpy_params=memcpy.get_params(x),.kind=@as(u16,2),
        .first=(y-64)%43==0,.last=(y-64)%43==42,.parity=@as(u16,((y-64)%43)%2),.embedding_return=false,.return_root=false});
    }else if(x==2 and y==0){
      @set_tile_code(x,y,"attention_controller_full.csl",.{.memcpy_params=memcpy.get_params(x),.first_layer=layer==0});
    }else if(x==2 and is_node(y)){
      @set_tile_code(x,y,"prefix_collector.csl",.{.memcpy_params=memcpy.get_params(x),.parity=node_index(y)%2,.tail=y==1139});
    }else if(x==3 and y<8){
      @set_tile_code(x,y,"kv.csl",.{.memcpy_params=memcpy.get_params(x)});
    }else '''+placements[start:].lstrip().removeprefix('if')
    # The insertion ends with "else if"; preserve the original router conditional.
    placements=placements.replace('}else (x==1','}else if(x==1')
    placements=placements.replace('"expert_join.csl"','"expert_join_full.csl"').replace('"moe_controller.csl"','"moe_controller_full.csl"').replace('.ingress=x==0 and y==1158','.ingress=false')
    placements=re.sub(r'@set_tile_code\(x,y,', '@set_tile_code(b+x,y,',placements)
    placements=placements.replace('memcpy.get_params(x)','memcpy.get_params(b+x)')
    preamble='''// Generated by tools/build_full_layout.py. Full original GPT-OSS-20B, 24 layers.
const memcpy=@import_module("<memcpy/get_params>",.{.width=750,.height=1160});
fn is_node(y:i16) bool {return y<8 or (y<1140 and y%30==29) or (y>=106 and y<=1052 and (y-106)%43==0);}
// Rank in {0..7} union {29+30r} union {106+43r}; y=149 is the sole overlap.
fn node_index(y:i16) u16 {
  const first:i16=if(y<8) y else 8;
  const q:i16=if(y/30<38) y/30 else 38;
  const o:i16=if(y<=106) 0 else if((y-64)/43<23) (y-64)/43 else 23;
  return @as(u16,first+q+o-(if(y>149) 1 else 0));
}
layout {
  @set_rectangle(750,1160);
  for(@range(i16,24))|layer|{
    const b:i16=46+27*layer;
    for(@range(i16,27))|x|{for(@range(i16,1160))|y|{
'''
    layer_end='''
    @set_color_config(b+26,0,@get_color(12),.{.routes=.{.rx=.{RAMP},.tx=.{EAST}}});
    if(layer>0){
      for(@range(i16,2))|x|{@set_color_config(b+x,0,@get_color(12),.{.routes=.{.rx=.{WEST},.tx=.{EAST}}});}
      @set_color_config(b+2,0,@get_color(12),.{.routes=.{.rx=.{WEST},.tx=.{RAMP}}});
    }
  }
'''
    vocabulary='''
  // Original 201088 vocabulary rows in 1571 tiles; padded last-column rows relay.
  for(@range(i16,750))|x|{if(x<46 or x>=694){for(@range(i16,1160))|y|{
    if(x==0 and y==0){
      @set_tile_code(x,y,"token_endpoint.csl",.{.memcpy_params=memcpy.get_params(x),.west=true});
    }else if(x==749 and y==0){
      @set_tile_code(x,y,"token_endpoint.csl",.{.memcpy_params=memcpy.get_params(x),.west=false});
    }else if(x>=4 and x<46 and y<1140){
      @set_tile_code(x,y,"embedding.csl",.{.memcpy_params=memcpy.get_params(x),.valid=(x-4)*38+y/30<1571,.column=@as(u16,x-4)});
    }else if(x>=694 and x<736 and y<1140){
      @set_tile_code(x,y,"head.csl",.{.memcpy_params=memcpy.get_params(x),.valid=(x-694)*38+y/30<1571,
        .first=y%30==0,.last=y%30==29,.parity=@as(u16,y%2),.column=@as(u16,x-694)});
    }else if(x==736 and y==0){
      @set_tile_code(x,y,"head_controller.csl",.{.memcpy_params=memcpy.get_params(x)});
    }else if(x==736 and y<1140 and y%30==29){
      @set_tile_code(x,y,"head_collector.csl",.{.memcpy_params=memcpy.get_params(x),.parity=@as(u16,(y/30+1)%2),.tail=y==1139});
    }else{
      @set_tile_code(x,y,"idle.csl",.{.memcpy_params=memcpy.get_params(x),.ingress=false,.metadata=false});
    }
  }}}
  @set_color_config(0,0,@get_color(12),.{.routes=.{.rx=.{RAMP},.tx=.{EAST}}});
  for(@range(i16,1,48,1))|x|{@set_color_config(x,0,@get_color(12),.{.routes=.{.rx=.{WEST},.tx=.{EAST}}});}
  @set_color_config(48,0,@get_color(12),.{.routes=.{.rx=.{WEST},.tx=.{RAMP}}});
  // Token metadata goes west and down once, then 30 embedding slices go east.
  @set_color_config(48,0,@get_color(13),.{.routes=.{.rx=.{RAMP},.tx=.{WEST}}});
  @set_color_config(47,0,@get_color(13),.{.routes=.{.rx=.{EAST},.tx=.{WEST}}});
  for(@range(i16,4,47,1))|x|{for(@range(i16,1140))|y|{
    @set_color_config(x,y,@get_color(13),.{.routes=.{.rx=if(y==0) .{EAST} else .{NORTH},
      .tx=if(y==0 and x>4) .{RAMP,WEST,SOUTH} else if(y==1139) .{RAMP} else .{RAMP,SOUTH}}});
  }}
  for(@range(i16,4,46,1))|x|{for(@range(i16,1140))|y|{
    @set_color_config(x,y,@get_color(if((x-4)%2==0) 14 else 15),.{.routes=.{.rx=.{RAMP},.tx=.{EAST}}});
    if(x>4){@set_color_config(x,y,@get_color(if((x-4)%2==1) 14 else 15),.{.routes=.{.rx=.{WEST},.tx=.{RAMP}}});}
  }}
  for(@range(i16,1140))|y|{
    @set_color_config(46,y,@get_color(15),.{.routes=.{.rx=.{WEST},.tx=.{RAMP}}});
    if(y>0){
      const route_color=@get_color(if(y%2==1) 18 else 19);
      @set_color_config(46,y,route_color,.{.routes=.{.rx=.{RAMP},.tx=.{NORTH}}});
      @set_color_config(46,y-1,route_color,.{.routes=.{.rx=.{SOUTH},.tx=.{RAMP}}});
    }
  }
  @set_color_config(46,0,@get_color(14),.{.routes=.{.rx=.{RAMP},.tx=.{EAST}}});
  @set_color_config(47,0,@get_color(14),.{.routes=.{.rx=.{WEST},.tx=.{EAST}}});
  @set_color_config(48,0,@get_color(14),.{.routes=.{.rx=.{WEST},.tx=.{RAMP}}});
  // Final residual crosses the head bank once; final RMSNorm fans inputs west.
  for(@range(i16,694,736,1))|x|{@set_color_config(x,0,@get_color(12),.{.routes=.{.rx=.{WEST},.tx=.{EAST}}});}
  @set_color_config(736,0,@get_color(12),.{.routes=.{.rx=.{WEST},.tx=.{RAMP}}});
  @set_color_config(736,0,@get_color(3),.{.routes=.{.rx=.{RAMP},.tx=.{WEST}}});
  for(@range(i16,694,736,1))|x|{for(@range(i16,1140))|y|{
    const k:i16=y%30;const valid:bool=(x-694)*38+y/30<1571;
    if(valid){
      @set_color_config(x,y,@get_color(3),.{.routes=.{.rx=if(y==0) .{EAST} else .{NORTH},
        .tx=if(y==0 and x>694) .{RAMP,WEST,SOUTH} else if(y==1139 or (x==735 and y==389)) .{RAMP} else .{RAMP,SOUTH}},
        .filter=.{.kind=.{.counter=true},.count_data=true,.init_counter=@as(u16,(2880-k*96)%2880),.max_counter=95,.limit1=2879}});
      if(k<29){@set_color_config(x,y,@get_color(if(k%2==0) 4 else 5),.{.routes=.{.rx=.{RAMP},.tx=.{SOUTH}}});}
      if(k>0){@set_color_config(x,y,@get_color(if(k%2==1) 4 else 5),.{.routes=.{.rx=.{NORTH},.tx=.{RAMP}}});}
    }
    if(k==29){
      @set_color_config(x,y,@get_color(if((x-694)%2==0) 14 else 15),.{.routes=.{.rx=.{RAMP},.tx=.{EAST}}});
      if(x>694){@set_color_config(x,y,@get_color(if((x-694)%2==1) 14 else 15),.{.routes=.{.rx=.{WEST},.tx=.{RAMP}}});}
    }
  }}
  for(@range(i16,38))|row|{
    const y:i16=29+30*row;const parent:i16=if(row==0) 0 else y-30;
    const route_color=@get_color(if(row%2==0) 16 else 17);
    @set_color_config(736,y,@get_color(15),.{.routes=.{.rx=.{WEST},.tx=.{RAMP}}});
    @set_color_config(736,y,route_color,.{.routes=.{.rx=.{RAMP},.tx=.{NORTH}}});
    for(@range(i16,parent+1,y,1))|middle|{@set_color_config(736,middle,route_color,.{.routes=.{.rx=.{SOUTH},.tx=.{NORTH}}});}
    @set_color_config(736,parent,route_color,.{.routes=.{.rx=.{SOUTH},.tx=.{RAMP}}});
  }
  @set_color_config(736,0,@get_color(13),.{.routes=.{.rx=.{RAMP},.tx=.{EAST}}});
  for(@range(i16,737,750,1))|x|{@set_color_config(x,0,@get_color(13),.{.routes=.{.rx=.{WEST},.tx=if(x==749) .{RAMP} else .{EAST}}});}
'''
    exports='''
  @export_name("identity",[*]u32,false);@export_name("counters",[*]u32,false);
  @export_name("weights",[*]u16,false);@export_name("scales",[*]u16,false);@export_name("bias",[*]u16,false);@export_name("gain",[*]u16,false);
  @export_name("hidden",[*]u32,false);@export_name("workspace",[*]u32,false);@export_name("frequencies",[*]f32,false);
  @export_name("input",[*]f32,false);@export_name("output",[*]u32,false);@export_name("token",[*]u32,false);
  @export_name("keys",[*]u16,false);@export_name("values",[*]u16,false);@export_name("sinks",[*]u16,false);
  @export_name("logits",[*]u16,false);@export_name("ids",[*]u16,false);@export_name("probabilities",[*]u16,false);
  @export_name("routing",[*]u32,false);@export_name("gate_debug",[*]u16,false);@export_name("activation_debug",[*]u16,false);
  @export_name("step",fn(u16,u16,u16)void);
}
'''
    return preamble+placements+'  }}\n'+shift_routes(prefix_routes)+shift_routes(moe_routes)+layer_end+vocabulary+exports

if __name__=='__main__':
    path=ROOT/'experiments/full_model/layout.csl';path.parent.mkdir(parents=True,exist_ok=True);path.write_text(build())
    print(path)
